project:
  type: website
  output-dir: docs

# Meta
description-meta: "Samee Ullah is a Computational Structural Biologist and a former Bioinformatician at National Institute of Health. He studies the protein and nucleic acids structures, dynamics and interaction with small molecules using the state of the art methods of Molecular dynamics simulations, and physics based binding energy calculations."
author-meta: "Samee Ullah"

website:
  title: "Samee Ullah"
  image: "/files/ullah-samee-profile.jpeg"
  description: "Samee Ullah is a Computational Structural Biologist and a former Bioinformatician at National Institute of Health. He studies the protein and nucleic acids structures, dynamics and interaction with small molecules using the state of the art methods of Molecular dynamics simulations, and physics based binding energy calculations."
 
  navbar:
    background: light

    left:
#      - text: Home
#        href: index.qmd
      - text: News&Events
        menu:
          - text: News
            href: posts.qmd#category=news
          - text: Events
            href: posts.qmd#category=event
      - text: Publications
        menu:
          - text: Selected Papers
            href: posts.qmd#category=paper
          - text: Commentary
            href: posts.qmd#category=commentary
          - text: Testimony
            href: posts.qmd#category=testimony
          - text: List of Publication
            href: publications.qmd
      - text: Teaching
        href: teaching.qmd
      - text: Posts
        href: posts.qmd       
      - text: Contact
        href: contact.qmd   
    
    right: 
      - text: CV
        href: files/Ullah-Samee-CV.pdf 
      - icon: github
        href: https://github.com/ullahsamee
      - icon: twitter 
        href: https://twitter.com/CryoKhan
      - icon: rss
        href: posts.xml 
  
  page-navigation: true
  
  page-footer: 
    left: "&copy; 2023 [Samee Ullah](https://ullahsamee.github.io/)." 
    right:  
      - icon: github
        href: https://github.com/ullahsamee
      - icon: twitter 
        href: https://twitter.com/CryoKhan
      - icon: rss
        href: posts.xml  
  
  search:
    location: navbar
    type: textbox
  
  reader-mode: true
  
  repo-url: https://github.com/ullahsamee
#  repo-actions: [edit, issue, source]
  
  open-graph: true
  
  twitter-card: true 
#  card-style: summary      
  
  site-url: "https://ullahsamee.github.io"
  
  google-analytics:
    tracking-id: "G-M8KED5NGHT"
    anonymize-ip: true 

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    footnotes-hover: true
    link-external-icon: false
    link-external-newwindow: true
    #link-external-filter: '^(?:http:|https:)\/\/ullahsamee\.github\.io\/custom'



